# Generated by Django 4.1.7 on 2023-06-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0002_article_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="num_like",
            field=models.IntegerField(default=0),
        ),
    ]
